### ISSUE TITLE
Question (real)

### ISSUE THREAD

**Issue by KylomaskGamer** [Carroted/simulo_bevy#1]
How many Simulos are needed to release Simulo (real)?

You made (real):
- Simulo Unity (real)
- Simulo (real)
- Simulo NT (real)
- Simulo Bevy (real)

I feel like Simulo 1.0.0 (real) wont be (real)eased next year.
I hope its not going to be like that war i witnessed (real) where we had to do 3-4 rounds to settle it (real)

Note: I am not mad that there is 4 versions (real), its just getting annoying for me (real)
Secondary note: Why am i using (real) so much

**Comment by aMySour** [comment]
I never said 1.0.0 would be next year

if you had been actually paying attention, you would've seen that what I have been saying the entire time since the very first web rewrite was that the end goal was gonna be 100% rust game

the goal was always gonna be to slowly rewrite in rust over time as I get better with rust

and now that I'm capable of using bevy, I'm fully rewriting it in that

if I had been able to do this back in the days of bimulo I would've definitely done it back then

and there's 0 reason for any more rewrites now, it's as fast as I'm capable of pushing it

runs at 1400fps for Nicolas, 700fps for me

why would I rewrite again? we did it, we reached literally what will be the best simulo I could ever make

one that will work natively (hyperspeed desktop versions), on mobile, and on web

you mentioned liking Simulo NT, but it has way too many problems:

- can't make fast desktop versions and just be electron, which would suck for everyone
- less smooth than bevyulo and Algodoo
- freezes my browser sometimes (bevyulo doesn't do that)
- mobile versions world work extremely poorly

plus lately I prefer writing bevy code

and bevyulo development is actually kinda faster since I don't have to maintain an entire custom game engine just for the game

so what I'm saying is, we did it, this is the final simulo, you have my 100% guarantee on that

even when developing NT the entire time I was thinking about how it'd be way better to make it in rust

**Comment by KylomaskGamer** [comment]
ok thanks
i forgor about the community
